name: Atualizar Repositório

on:
  schedule:
    - cron: '0 0 * * *' # Define o cron para executar diariamente à meia-noite

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Atualizar repositório
        run: |
          git config --global user.email "pedrohmota2005@gmail.com"
          git config --global user.name "PedrooMota"
          git pull
          git add .
          git commit -m "Atualização automática"
          git push
